build documentation with travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -93,4 +93,32 @@ install:
 
 script:
   - cd "${TRAVIS_BUILD_DIR}"
-  - (cd build && cmake --build . --target check -- -j2)
+
+  ############################################################################
+  # Only push the documentation when we're on master, otherwise just make sure
+  # it builds properly.
+  ############################################################################
+  - |
+    if [[ "${DOCUMENTATION}" == "true" ]]; then
+      (cd build && ! cmake --build . --target doc 2>&1 | grep -E "warning|error") || exit 1
+      if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
+        # Suppress output to avoid leaking the token when the command fails
+        git clone https://malarsson:${GITHUB_TOKEN}@github.com/malarsson/umlaut --depth 1 --branch=gh-pages doc/html &>/dev/null
+        rm -rf doc/html/{search,*.png,*.css,*.js,*.html}
+        cp -R build/doc/html/* doc/html/
+        pushd doc/html
+        git add --all .
+        git commit --allow-empty -m "Update documentation to ${TRAVIS_COMMIT:0:7}"
+        # Suppress output to avoid leaking the token
+        travis_retry git push origin gh-pages &>/dev/null
+        popd
+      fi
+    fi
+
+  ############################################################################
+  # Build and run the unit tests.
+  ############################################################################
+  - |
+    if [[ "${UNIT_TESTS}" == "true" ]]; then
+      (cd build && cmake --build . --target check -- -j2)
+    fi
