only push docs if building docs was successful

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -97,17 +97,23 @@ script:
   ############################################################################
   - |
     if [[ "${DOCUMENTATION}" == "true" ]]; then
-      (cd "${TRAVIS_BUILD_DIR}/build" && cmake --build . --target doc)
-      # Suppress output to avoid leaking the token when the command fails
-      git clone https://malarsson:${GITHUB_TOKEN}@github.com/malarsson/umlaut --depth 1 --branch=gh-pages doc/html &>/dev/null
-      rm -rf doc/html/{search,*.png,*.css,*.js,*.html}
-      cp -R build/html/* doc/html/
-      pushd doc/html
-      git add --all .
-      git commit --allow-empty -m "update documentation to ${TRAVIS_COMMIT:0:7}"
-      # Suppress output to avoid leaking the token
-      git push origin gh-pages &>/dev/null
-      popd
+      (cd build && ! cmake --build . --target doc 2>&1 | grep -E "warning|error") || exit 1
+
+      if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
+        # Suppress output to avoid leaking the token when the command fails
+        git clone https://malarsson:${GITHUB_TOKEN}@github.com/malarsson/umlaut --depth 1 --branch=gh-pages doc/html &>/dev/null
+
+        rm -rf doc/html/{search,*.png,*.css,*.js,*.html}
+        cp -R build/html/* doc/html/
+
+        pushd doc/html
+        git add --all .
+        git commit --allow-empty -m "update documentation to ${TRAVIS_COMMIT:0:7}"
+
+        # Suppress output to avoid leaking the token
+        git push origin gh-pages &>/dev/null
+        popd
+      fi
     fi
 
   ############################################################################
@@ -115,5 +121,5 @@ script:
   ############################################################################
   - |
     if [[ "${UNIT_TESTS}" == "true" ]]; then
-      (cd "${TRAVIS_BUILD_DIR}/build" && cmake --build . --target check -- -j2)
+      (cd build && cmake --build . --target check -- -j2)
     fi
