build documentation and push to gh-pages branch with travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,6 +12,11 @@ matrix:
     - env: UNIT_TESTS=true COMPILER=clang++-5.0
       addons: &defaults { apt: { packages: ["clang-5.0"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }
 
+    ##########################################################################
+    # Generate the documentation
+    ##########################################################################
+    - env: DOCUMENTATION=true COMPILER=default
+      addons: *defaults
 
 install:
   ############################################################################
@@ -69,6 +74,13 @@ install:
       export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/llvm/install/lib"
     fi
 
+before-script:
+  ############################################################################
+  # Set the git identity (for pushing the documentation and the benchmarks)
+  ############################################################################
+  - git config --global user.name "Travis bot"
+  - git config --global user.email "<>"
+
   ############################################################################
   # Go back to the root of the project and setup the build directory
   ############################################################################
@@ -77,9 +89,30 @@ install:
 
 script:
   ############################################################################
+  # Only push the documentation when we're on master, otherwise just make sure
+  # it builds properly.
+  ############################################################################
+  - |
+    if [[ "${DOCUMENTATION}" == "true" ]]; then
+      (cd build && ! cmake --build . --target doc 2>&1 | grep -E "warning|error") || exit 1
+      if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" ]]; then
+        # Suppress output to avoid leaking the token when the command fails
+        git clone https://malarsson:${GITHUB_TOKEN}@github.com/malarsson/umlaut --depth 1 --branch=gh-pages doc/html &>/dev/null
+        rm -rf doc/html/{search,*.png,*.css,*.js,*.html}
+        cp -R build/doc/html/* doc/html/
+        pushd doc/html
+        git add --all .
+        git commit --allow-empty -m "Update documentation to ${TRAVIS_COMMIT:0:7}"
+        # Suppress output to avoid leaking the token
+        travis_retry git push origin gh-pages &>/dev/null
+        popd
+      fi
+    fi
+
+  ############################################################################
   # Build and run the unit tests.
   ############################################################################
   - |
     if [[ "${UNIT_TESTS}" == "true" ]]; then
-      (cd "${TRAVIS_BUILD_DIR}/build" && cmake --build . --target check -- -j2)
+      (cd build && cmake --build . --target check -- -j2)
     fi
